Senzing/kubernetes-demo

docs/helm-db2-demo/README.md
helm-values-templates/ibm-db2express-c.yaml
helm-values-templates/senzing-api-server-db2.yaml
helm-values-templates/stream-loader-db2.yaml
kubernetes-templates/persistent-volume-claim-db2-data-stor.yaml

issue-1 Working DB2

---

docs/helm-db2-demo/README.md

issue-1 Update table-of-contents

---

docs/helm-db2-demo/README.md
docs/helm-postgresql-demo/README.md
helm-values-templates/mock-data-generator.yaml
helm-values-templates/senzing-package-sleep.yaml

issue-1 Improved documentation

---

docs/helm-db2-demo/README.md
helm-values-templates/mock-data-generator.yaml
helm-values-templates/phppgadmin.yaml
helm-values-templates/senzing-api-server-db2.yaml
helm-values-templates/senzing-api-server-mysql.yaml
helm-values-templates/senzing-api-server-postgresql.yaml
helm-values-templates/stream-loader-db2.yaml
helm-values-templates/stream-loader-mysql.yaml
helm-values-templates/stream-loader-postgresql.yaml

Issue 1.dockter.1

---

docs/helm-db2-demo/README.md

issue-1 Add TLS support

---

docs/helm-db2-demo/README.md
docs/helm-postgresql-demo/README.md
helm-values-templates/senzing-debug-mysql.yaml
helm-values-templates/senzing-debug-postgresql.yaml
helm-values-templates/stream-loader-mysql.yaml

issue-1 Improved DB2 instructions

---

README.md

issue-1 Improved overview

---

docs/helm-db2-demo/README.md
docs/helm-postgresql-demo/README.md

issue-1 Document cleanup

---

README.md
docs/helm-db2-demo/README.md
docs/helm-postgresql-demo/README.md

issue-1 Use DOCKER_IMAGE_NAME

---

README.md

issue-14 Minor fix

---

docs/helm-kafka-db2/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-postgresql/README.md
helm-values-templates/senzing-package-sleep.yaml
helm-values-templates/senzing-package.yaml

issue-14 Working RabbitMQ

---

helm-values-templates/mock-data-generator-kafka.yaml
helm-values-templates/mock-data-generator-rabbitmq.yaml

issue-14 Removed _shuffled.json reference

---

docs/helm-rabbitmq-postgresql/README.md
helm-values-templates/rabbitmq.yaml
kubernetes-templates/persistent-volume-claim-opt-senzing.yaml
kubernetes-templates/persistent-volume-claim-rabbitmq.yaml
kubernetes-templates/persistent-volume-opt-senzing.yaml
kubernetes-templates/persistent-volume-rabbitmq.yaml

Issue 14.dockter.1

---

docs/helm-rabbitmq-mysql/README.md

issue-14 Add MySQL/RabbitMQ example

---

README.md
helm-values-templates/senzing-base.yaml

Issue 14.dockter.2

---

docs/helm-rabbitmq-postgresql/README.md

issue-14 Add non-root method to extract RPM

---

docs/helm-kafka-db2/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql/README.md
docs/helm-rabbitmq-sqlite/README.md
helm-values-templates/ibm-db2-driver-installer.yaml
helm-values-templates/init-container-db2.yaml
helm-values-templates/init-container-mysql.yaml
helm-values-templates/init-container-postgresql.yaml
helm-values-templates/init-container-sqlite.yaml
helm-values-templates/senzing-yum-localinstall.yaml
helm-values-templates/senzing-yum.yaml

issue-14 Improve clone repository instructions 

---

docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-postgresql/README.md

issue-14 Improve Db2 instructions

---

docs/helm-rabbitmq-db2/README.md

issue-14 Working instructions

---

helm-values-templates/mock-data-generator-kafka.yaml
helm-values-templates/mock-data-generator-rabbitmq.yaml

issue-14 Minor

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md

#38 Refactor to template

---

docs/helm-rabbitmq-sqlite-cluster/README.md
helm-values-templates/senzing-api-server-sqlite-cluster.yaml

issue-44 Support `SENZING_ENGINE_CONFIGURATION_JSON`

---

README.md

#48 Remove SQLite references

---

helm-values-templates/senzing-yum-localinstall.yaml

#43 Update Senzing RPM

---

README.md
docs/helm-kafka-db2/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql/README.md
docs/helm-rabbitmq-sqlite-cluster/README.md
docs/helm-rabbitmq-sqlite/README.md

Issue 54.dockter.1

---

CHANGELOG.md

#53 Prepare for version

---

docs/helm-kafka-db2/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql/README.md
docs/helm-rabbitmq-sqlite-cluster/README.md
docs/helm-rabbitmq-sqlite/README.md
helm-values-templates/kafka.yaml
helm-values-templates/stream-producer-kafka.yaml
helm-values-templates/stream-producer-rabbitmq.yaml

Issue number: #52 
Move to the new stream-producer helm chart
Replaces mock-data-generator with stream-producer

Issue 52.jadair.1

---

helm-values-templates/stream-loader-kafka-db2.yaml
helm-values-templates/stream-loader-kafka-mysql.yaml
helm-values-templates/stream-loader-kafka-postgresql.yaml
helm-values-templates/stream-loader-rabbitmq-db2.yaml
helm-values-templates/stream-loader-rabbitmq-mysql.yaml
helm-values-templates/stream-loader-rabbitmq-postgresql.yaml
helm-values-templates/stream-loader-rabbitmq-sqlite-cluster.yaml
helm-values-templates/stream-loader-rabbitmq-sqlite.yaml

Change ENTITY_TYPE to GENERIC

---

docs/helm-rabbitmq-postgresql/README.md

Issue 62.dockter.1

---

docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql/README.md
docs/helm-rabbitmq-sqlite-cluster/README.md
docs/helm-rabbitmq-sqlite/README.md

Copy changes for stable to bitnami

---

CHANGELOG.md

#77 Prepare for versioned release 1.4.0

---

docs/azure-helm-message-bus-mssql/README.md
docs/azure-helm-rabbitmq-postgresql/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql/README.md

Issue 77.dockter.3

---

bin/airgapped/docker-images.sh
bin/airgapped/docker-load.sh
bin/airgapped/populate-minikube-registry.sh
bin/airgapped/save-environment-variables.sh
bin/docker-tag-and-push.sh
bin/make-helm-values-files.sh
bin/make-kubernetes-manifest-files.sh
bin/save-environment-variables.sh
docs/helm-rabbitmq-postgresql-airgapped/README.md
helm-values-templates/bitnami-postgresql.yaml
helm-values-templates/bitnami-rabbitmq.yaml
helm-values-templates/phppgadmin.yaml
helm-values-templates/senzing-console-postgresql-privileged.yaml
helm-values-templates/senzing-installer.yaml
helm-values-templates/senzing-stream-producer-rabbitmq-airgapped.yaml

Issue 100.dockter.1

---

helm-values-templates/senzing-installer-mssql.yaml

#100 Show how to configure for MS SQL

---

.gitignore
bin/airgapped/download-senzing-files.sh
docs/azure-helm-message-bus-mssql/README.md
docs/azure-helm-rabbitmq-postgresql/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql-airgapped/README.md
docs/helm-rabbitmq-postgresql-multi-tenant/README.md
docs/helm-rabbitmq-postgresql/README.md

#107 Update latest to stable

---

docs/helm-rabbitmq-postgresql-multi-tenant/README.md

Issue 99.dockter.2

---

bin/docker-images-for-helm-kafka-postgresql.sh
bin/docker-images-for-helm-rabbitmq-db2.sh
bin/docker-images-for-helm-rabbitmq-mysql.sh
bin/save-environment-variables.sh
docs/azure-helm-message-bus-mssql/README.md
docs/azure-helm-rabbitmq-postgresql/README.md
docs/helm-kafka-postgresql/README.md
docs/helm-rabbitmq-db2/README.md
docs/helm-rabbitmq-mysql/README.md
docs/helm-rabbitmq-postgresql-multi-tenant/README.md
docs/helm-rabbitmq-postgresql/README.md
helm-values-templates/senzing-stream-loader-azure-queue-mssql.yaml
helm-values-templates/senzing-stream-loader-kafka-postgresql.yaml
helm-values-templates/senzing-stream-loader-rabbitmq-db2.yaml
helm-values-templates/senzing-stream-loader-rabbitmq-mysql.yaml
helm-values-templates/senzing-stream-loader-rabbitmq-postgresql-multi-tenant.yaml
helm-values-templates/senzing-stream-loader-rabbitmq-postgresql.yaml
helm-values-templates/senzing-stream-producer-azure-queue.yaml
helm-values-templates/senzing-stream-producer-kafka.yaml
helm-values-templates/senzing-stream-producer-rabbitmq-airgapped.yaml
helm-values-templates/senzing-stream-producer-rabbitmq-multi-tenant.yaml
helm-values-templates/senzing-stream-producer-rabbitmq.yaml

Issue 106.dockter.1

---

docs/azure-helm-message-bus-mssql/README.md
helm-values-templates/senzing-stream-loader-azure-queue-mssql.yaml
helm-values-templates/senzing-stream-producer-azure-queue.yaml

#121 Update instructions to use SENZING_AZURE_QUEUE_CONNECTION_STRING
